version: "3"
services:
  pgweb:
    container_name: esus_pgweb
    restart: always
    image: sosedoff/pgweb
    ports:
      - "${PGWEB_PORT}:8081"
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@psql:5432/${POSTGRES_DB}?sslmode=disable
    depends_on:
      - psql
  api:
    container_name: esus_api
    restart: always
    build:
      context: api
      dockerfile: Dockerfile
    volumes:
      - ./api:/app
      - ./api/nginx.conf:/etc/nginx/sites-enabled/default
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@psql:5432/${POSTGRES_DB}?sslmode=disable
    stdin_open: true
    ports:
      - "${API_PORT}:80"
    depends_on:
      - psql
