version: "3"
services:
  pgweb:
    container_name: esus_dashboard_pgweb
    restart: always
    image: sosedoff/pgweb
    ports:
      - "${PGWEB_PORT}:8081"
    environment:
      - PGWEB_DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@psql:5432/${POSTGRES_DB}?sslmode=disable
  api:
    container_name: esus_dashboard_api
    restart: always
    build:
      context: api
      dockerfile: Dockerfile
    volumes:
      - ./api:/app
      - ./api/nginx.conf:/etc/nginx/sites-enabled/default
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@psql:5432/${POSTGRES_DB}?sslmode=disable
      - MASTER_KEY=${MASTER_KEY}
      - SECRET=${SECRET}
    stdin_open: true
    ports:
      - "${API_PORT}:80"
