version: "3"
services:
  api:
    container_name: esus_api
    restart: always
    build:
      context: api
      dockerfile: Dockerfile
    volumes:
      - ./api:/app
      - ./api/nginx.conf:/etc/nginx/sites-enabled/default
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@psql:5432/${POSTGRES_DB}?sslmode=disable
    stdin_open: true
    ports:
      - "${API_PORT}:5000"
    depends_on:
      - psql
